# Generated by Django 4.2 on 2023-07-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sttable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
