# Generated by Django 4.2 on 2023-07-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sttable', '0002_students_created_time_students_updated_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('number', models.IntegerField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
